name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: Build & Deploy Release to OSSRH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Get version from tag name
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF##*/v}

      - name: Build & Publish
        run: ./gradlew publish -Pversion=${{ steps.vars.outputs.version }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}


