name: run tests

on: [push, pull_request]


jobs:
  run-tests:
    strategy:
      matrix:
        java-version: [8,9,11]
        distribution: [zulu, adopt]
    name: run tests with ${{ matrix.java-version }} ${{ matrix.distribution }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}

      - run: ./gradlew test