name: run tests

on: [push, pull_request]


jobs:
  run-tests:
    strategy:
      matrix:
        java-version: [8,9,11]
    name: run tests with ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - run: ./gradlew test