name: Validate Gradle Wrapper

on: pull_request

jobs:
  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1
